### ISSUE TITLE
Timeout on rsa_example

### ISSUE THREAD

**Issue by prototype117** [tkzilla/visa_control_examples#1]
Hello,

I am experiencing an issue regarding the rsa_example function with an RSA 306.  I'm able to connect to the instrument and configure it according to the parameters set in the example, however during the for loop, I experience a timeout error.  I'll note too that this leads to issues with reconnecting to the instrument, as the disconnect function that is defined later in the script doesn't run; this can be fixed, but it did present a problem for me initially while attempting to debug the for loop problem.  Thanks for the code though, it's immensely helpful in understanding socket communications on Tek instruments.
[rsa_example_error.txt](https://github.com/tkzilla/visa_control_examples/files/1555960/rsa_example_error.txt)

**Comment by tkzilla** [comment]
This error is caused by a mismatched command in the get_error() function. Unfortunately there is not a standard query for checking errors across instrument families. "allev?" works for oscilloscopes and "system:error:all?" works for spectrum analyzers and AWGs. Since scopes can also be used as spectrum analyzers, choosing the error checking command based on the instrument name is not a sufficiently robust solution. I have removed the get_error() function and added the correct procedure in the rsa_example() and scope_example() functions.
